# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  GLFW_config = debug
  glad_config = debug
  cimgui_config = debug
  Engine_config = debug
  EngineEditor_config = debug

else ifeq ($(config),release)
  GLFW_config = release
  glad_config = release
  cimgui_config = release
  Engine_config = release
  EngineEditor_config = release

else ifeq ($(config),dist)
  GLFW_config = dist
  glad_config = dist
  cimgui_config = dist
  Engine_config = dist
  EngineEditor_config = dist

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := GLFW glad cimgui Engine EngineEditor

.PHONY: all clean help $(PROJECTS) Dependencies

all: $(PROJECTS)

Dependencies: Engine EngineEditor GLFW cimgui glad

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C Dependencies/GLFW -f Makefile config=$(GLFW_config)
endif

glad:
ifneq (,$(glad_config))
	@echo "==== Building glad ($(glad_config)) ===="
	@${MAKE} --no-print-directory -C Dependencies/glad -f Makefile config=$(glad_config)
endif

cimgui:
ifneq (,$(cimgui_config))
	@echo "==== Building cimgui ($(cimgui_config)) ===="
	@${MAKE} --no-print-directory -C Dependencies/cimgui -f Makefile config=$(cimgui_config)
endif

Engine:
ifneq (,$(Engine_config))
	@echo "==== Building Engine ($(Engine_config)) ===="
	@${MAKE} --no-print-directory -C Engine -f Makefile config=$(Engine_config)
endif

EngineEditor: Engine glad GLFW cimgui
ifneq (,$(EngineEditor_config))
	@echo "==== Building EngineEditor ($(EngineEditor_config)) ===="
	@${MAKE} --no-print-directory -C EngineEditor -f Makefile config=$(EngineEditor_config)
endif

clean:
	@${MAKE} --no-print-directory -C Dependencies/GLFW -f Makefile clean
	@${MAKE} --no-print-directory -C Dependencies/glad -f Makefile clean
	@${MAKE} --no-print-directory -C Dependencies/cimgui -f Makefile clean
	@${MAKE} --no-print-directory -C Engine -f Makefile clean
	@${MAKE} --no-print-directory -C EngineEditor -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GLFW"
	@echo "   glad"
	@echo "   cimgui"
	@echo "   Engine"
	@echo "   EngineEditor"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"